import type { Metadata } from "next";
import { Boldonse, DM_Sans, Geist_Mono, Sniglet } from "next/font/google";
import "./globals.css";
import { LayoutContent } from "./layout-content";

const boldonse = Boldonse({
  weight: "400",
  variable: "--font-boldonse",
  subsets: ["latin"],
});

const sniglet = Sniglet({
  weight: "800",
  variable: "--font-logo",
  subsets: ["latin"],
});

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${boldonse.variable} ${sniglet.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className={"overflow-x-clip antialiased"}>
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
